### ISSUE TITLE
I like the name of your library

### ISSUE THREAD

**Issue by sietse** [sjsyrek/maryamyriameliamurphies.js#25]
This is just to say that I really like [the name of your library](https://github.com/sjsyrek/maryamyriameliamurphies.js#what-the-name-of-this-library-means). (No, I don't know why I'm linking you to an explanation you wrote yourself.) It's rare enough to encounter literary allusions in programming projects, let alone one as good as this. I thought you should know your humour is appreciated :-)

**Comment by sjsyrek** [comment]
Aww thanks! That's so nice of you to say, and nice to hear. 🤗
